### ISSUE TITLE
List on Graylog Marketplace

### ISSUE THREAD

**Issue by lennartkoopmann** [CygnusNetworks/nagios-plugin-graylog2#1]
We have launched the beta of the Graylog Marketplace: https://marketplace.graylog.org/

The Marketplace is the central directory of all Graylog add-ons and integrations, including GELF libraries.

You would help us a lot if you could submit your add-on there. :)

**Comment by cygnusb** [comment]
Added

**Comment by lennartkoopmann** [comment]
Thank you! :+1: :shipit:
