### ISSUE TITLE
GRAYLOG2CHECK UNKNOWN: RuntimeError: Graylog2 API returned non-JSON value: No JSON object could be decoded

### ISSUE THREAD

**Issue by bubba198** [CygnusNetworks/nagios-plugin-graylog2#2]
GRAYLOG2CHECK UNKNOWN: RuntimeError: Graylog2 API returned non-JSON value: No JSON object could be decoded

Running the plug-in on:

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

Graylog 2.2.1

**Comment by s0l4r** [comment]
I have the same issue:
Graylog v2.2.3+7adc951

./check_graylog2 -u admin 
GRAYLOG2CHECK UNKNOWN: RuntimeError: Graylog2 API returned non-JSON value: No JSON object could be decoded

**Comment by cygnusb** [comment]
Can you please provide output of a packet capture/ngrep what is happening there? Most propably the API has changed and now works diffently. I have no 2.2.x installation here, so I cannot test this.
You can create a dump using:
ngrep -d lo port 12900
when running the plugin?

**Comment by s0l4r** [comment]
Thanks @cygnusb , I think Graylog has changed the API.
My REST API URL is http://0.0.0.0:9000/api/

When testing with another similar plugin to yours, it doesn't work either. The returning code from Graylog API is in HTML, but it should be JSON. I think that you have to pass "Accept: application/json" header, because when testing the API URL with curl, it gives JSON back.

```
curl -i -X POST -H 'Content-Type: application/json' -H 'Accept: application/json' 'http://localhost:9000/api/system/sessions' -d '{"username":"admin", "password":"xxx", "host":""}'
HTTP/1.1 200 OK
X-Graylog-Node-ID: 1234
Content-Type: application/json
Date: Tue, 30 May 2017 16:08:51 GMT
Content-Length: 98

{"valid_until":"2017-05-31T00:08:52.162+0000","session_id":"41b833f9-0f90-463c-84c2-ecabce2c53e3"}
```

```
ngrep -d eth0 port 9000
interface: eth0 (10.22.192.72/255.255.255.248)
filter: ( port 9000 and src 10.22.192.6 ) and ((ip || ip6) || (vlan && (ip || ip6)))
###
T 10.22.192.6:51462 -> 10.22.192.76:9000 [AP]
  GET /system HTTP/1.1..Accept-Encoding: identity..Host: 10.22.192.76:9000..Connection: close..User-Agent: Python-urllib/2.7....                                        
##

###
T 10.22.192.6:51463 -> 10.22.192.76:9000 [AP]
  GET /system HTTP/1.1..Accept-Encoding: identity..Host: 10.22.192.76:9000..Connection: close..User-Agent: Python-urllib/2.7....                                        
####

```

**Comment by bubba198** [comment]
agreed with @s0l4r -- I am running two OVA's one is 2.2 and the other is 2.1 and both exhibit the same issue with the plug-in

**Comment by cygnusb** [comment]
We added support for graylog2 2.x. This works at least with a test system of ours. Please check if this also works for you using the latest commit in master.

**Comment by cygnusb** [comment]
As there was no feedback and the issue seems to be closed on our side, I will close this issue
